const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const code=fs.readFileSync(path.join(root,'apps-script','Code.gs'),'utf8');
const dist=fs.readFileSync(path.join(root,'distribution','Code.gs'),'utf8');
const reqSchema=JSON.parse(fs.readFileSync(path.join(root,'shared','contracts','merge','merge-treatment-request-v1.schema.json'),'utf8'));
const resultSchema=JSON.parse(fs.readFileSync(path.join(root,'shared','contracts','merge','merge-treatment-result-v1.schema.json'),'utf8'));
function ok(cond,msg){if(!cond){console.error('FAIL:',msg);process.exit(1)}}
ok(code.includes("const SBM_VERSION = '5.10.0-RC8.15';"),'version RC8.15');
ok(code.includes("'Merge依頼JSON','Merge結果JSON'"),'Doctor_Cases merge columns');
ok(code.includes("explicitNextActionV2==='MERGE'"),'Doctor V2 MERGE routing');
ok(code.includes("explicitNextAction==='MERGE'"),'Doctor V1 MERGE routing');
ok(code.includes("code='MERGE_REQUEST_READY'"),'merge request ready state');
ok(code.includes('function sbmDoctorBuildMergeTreatmentRequest_'),'merge package builder');
ok(code.includes("contract_name:'SIMS_MERGE_TREATMENT_REQUEST_V1'"),'merge request contract');
ok(code.includes("primary_article_candidate:primary"),'primary article candidate');
ok(code.includes('target_articles:targetArticles'),'target article list');
ok(code.includes('source_content:req.attachments&&req.attachments.article_body'),'secondary article body evidence');
ok(code.includes('evidence_package:req.evidence_package'),'secondary GSC evidence');
ok(code.includes("route:'MERGE'"),'standard Doctor->SBM->Merge route');
ok(code.includes('function sbmDoctorSaveGeneratedMergeRequest_'),'merge package persistence');
ok(code.includes("'MERGE_IN_PROGRESS'"),'merge in progress state');
ok(code.includes('function sbmDoctorStoreMergeTreatmentResult_'),'merge result receiver');
ok(code.includes("SIMS_MERGE_TREATMENT_RESULT_V1"),'merge result contract guard');
ok(code.includes("'MERGE_RESULT_RECEIVED'"),'safe post-result state');
ok(code.includes("'Merge処置内容の実施待ち'"),'no automatic destructive execution');
ok(code.includes('function sbmDoctorSubmitSiteDiagnosisMergeResult'),'Site Diagnosis result enters SBM merge receiver');
ok(code.includes('mreq=sbmDoctorBuildMergeTreatmentRequest_(source,o,n)'),'Site Diagnosis reuses standard SBM merge builder');
ok(code.includes('id="mergeSection"'),'standard precision diagnosis Merge result UI');
ok(code.includes('id="mergeResultStep"'),'Site Diagnosis Merge result UI');
ok(reqSchema.title==='SIMS_MERGE_TREATMENT_REQUEST_V1','existing request schema unchanged/usable');
ok(resultSchema.title==='SIMS_MERGE_TREATMENT_RESULT_V1','existing result schema unchanged/usable');
ok(code===dist,'apps-script/distribution Code.gs identical');
console.log('PASS product5100_rc815_merge_workflow_test');
